//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkhamHorrorCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArkhamHorrorCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;monster&gt;
        ///  &lt;number&gt;
        ///    &lt;base&gt;3&lt;/base&gt;
        ///  &lt;/number&gt;
        ///  &lt;name&gt;Byakee&lt;/name&gt;
        ///  &lt;movement&gt;Flying&lt;/movement&gt;
        ///  &lt;awareness&gt;-2&lt;/awareness&gt;
        ///  &lt;dimension&gt;Circle&lt;/dimension&gt;
        ///  &lt;horror&gt;
        ///    &lt;rating&gt;-1&lt;/rating&gt;
        ///    &lt;damage&gt;1&lt;/damage&gt;
        ///  &lt;/horror&gt;
        ///  &lt;toughness&gt;1&lt;/toughness&gt;
        ///  &lt;combat&gt;
        ///    &lt;rating&gt;0&lt;/rating&gt;
        ///    &lt;damage&gt;2&lt;/damage&gt;
        ///  &lt;/combat&gt;
        ///  &lt;text&gt;
        ///    &lt;eng&gt;It shrieked and flapped its wings. I thought of the empty shell of a beetle, and the soft loam of rotting earth. It cocked its carapaced head at m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Byakhee {
            get {
                return ResourceManager.GetString("Byakhee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;monster&gt;
        ///  &lt;number&gt;
        ///    &lt;base&gt;2&lt;/base&gt;
        ///  &lt;/number&gt;
        ///  &lt;name&gt;Chtonian&lt;/name&gt;
        ///  &lt;movement&gt;Unique&lt;/movement&gt;
        ///  &lt;awareness&gt;1&lt;/awareness&gt;
        ///  &lt;dimension&gt;Triangle&lt;/dimension&gt;
        ///  &lt;horror&gt;
        ///    &lt;rating&gt;-2&lt;/rating&gt;
        ///    &lt;damage&gt;2&lt;/damage&gt;
        ///  &lt;/horror&gt;
        ///  &lt;toughness&gt;3&lt;/toughness&gt;
        ///  &lt;combat&gt;
        ///    &lt;rating&gt;-3&lt;/rating&gt;
        ///    &lt;damage&gt;3&lt;/damage&gt;
        ///  &lt;/combat&gt;
        ///  &lt;text&gt;
        ///    &lt;eng&gt;Instead of moving, roll a die. On a 4-6, all investigators in Arkham lose 1 Stamina.&lt;/eng&gt;
        ///  &lt;/text&gt;
        ///&lt;/monster&gt;.
        /// </summary>
        internal static string Chtonian {
            get {
                return ResourceManager.GetString("Chtonian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;monster&gt;
        ///  &lt;number&gt;
        ///    &lt;base&gt;6&lt;/base&gt;
        ///  &lt;/number&gt;
        ///  &lt;name&gt;Cultist&lt;/name&gt;
        ///  &lt;movement&gt;Normal&lt;/movement&gt;
        ///  &lt;awareness&gt;-3&lt;/awareness&gt;
        ///  &lt;dimension&gt;Moon&lt;/dimension&gt;
        ///  &lt;toughness&gt;1&lt;/toughness&gt;
        ///  &lt;combat&gt;
        ///    &lt;rating&gt;1&lt;/rating&gt;
        ///    &lt;damage&gt;1&lt;/damage&gt;
        ///  &lt;/combat&gt;
        ///  &lt;text&gt;
        ///    &lt;eng&gt;Ia! Ia! Cthulhu Fthagn! Ph&apos;nglui mglw&apos;nfah Cthulhu R&apos;lyeh wgah&apos;nagl fhtagn!&lt;/eng&gt;
        ///  &lt;/text&gt;
        ///&lt;/monster&gt;.
        /// </summary>
        internal static string Cultist {
            get {
                return ResourceManager.GetString("Cultist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;monster&gt;
        ///  &lt;number&gt;
        ///    &lt;base&gt;6&lt;/base&gt;
        ///  &lt;/number&gt;
        ///  &lt;name&gt;Dark Young&lt;/name&gt;
        ///  &lt;movement&gt;Stationary&lt;/movement&gt;
        ///  &lt;awareness&gt;-2&lt;/awareness&gt;
        ///  &lt;dimension&gt;Hexagon&lt;/dimension&gt;
        ///  &lt;horror&gt;
        ///    &lt;rating&gt;0&lt;/rating&gt;
        ///    &lt;damage&gt;3&lt;/damage&gt;
        ///  &lt;/horror&gt;
        ///  &lt;toughness&gt;3&lt;/toughness&gt;
        ///  &lt;combat&gt;
        ///    &lt;rating&gt;-1&lt;/rating&gt;
        ///    &lt;damage&gt;3&lt;/damage&gt;
        ///  &lt;/combat&gt;
        ///  &lt;text&gt;
        ///    &lt;eng&gt;The trees trembled, leaves fluttering around us. The earth shook as the thuds of giant hooved feet grew ever closer...&lt;/eng&gt;
        ///  &lt;/text&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dark_Young {
            get {
                return ResourceManager.GetString("Dark_Young", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;monster&gt;
        ///  &lt;number&gt;
        ///    &lt;base&gt;2&lt;/base&gt;
        ///  &lt;/number&gt;
        ///  &lt;name&gt;Dimensional Shambler&lt;/name&gt;
        ///  &lt;movement&gt;Fast&lt;/movement&gt;
        ///  &lt;awareness&gt;-3&lt;/awareness&gt;
        ///  &lt;dimension&gt;Square&lt;/dimension&gt;
        ///  &lt;horror&gt;
        ///    &lt;rating&gt;-2&lt;/rating&gt;
        ///    &lt;damage&gt;1&lt;/damage&gt;
        ///  &lt;/horror&gt;
        ///  &lt;toughness&gt;1&lt;/toughness&gt;
        ///  &lt;combat&gt;
        ///    &lt;rating&gt;-2&lt;/rating&gt;
        ///    &lt;damage&gt;0&lt;/damage&gt;
        ///  &lt;/combat&gt;
        ///  &lt;text&gt;
        ///    &lt;eng&gt;If you fail a Combat or Evade check against Dimensional Shambler, you are lost in time and space.&lt;/eng&gt;
        ///  &lt;/text&gt;
        ///&lt;/monster&gt;.
        /// </summary>
        internal static string Dimensional_Shambler {
            get {
                return ResourceManager.GetString("Dimensional_Shambler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;deck type=&quot;neighborhood&quot; name_eng=&quot;Downtown&quot;&gt;
        ///  &lt;card&gt;
        ///    &lt;location name_eng=&quot;Arkham Asylum&quot;&gt;
        ///      &lt;text&gt;
        ///        &lt;eng&gt;
        ///          In the Doctor&apos;s study, you find a book of helpful notes gathered from inmate interviews. Make a Lore (+0) check and consult the following chart:
        ///          Successes:
        ///          0)   Their stories fill you with horror even as you learn a few bits of knowledge. Lose 1 Sanity and gain 1 Clue token.
        ///          1-2) You find several pieces of useful information. Gain 2 Clue t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Downtown {
            get {
                return ResourceManager.GetString("Downtown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Easttown {
            get {
                return ResourceManager.GetString("Easttown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FrenchHill {
            get {
                return ResourceManager.GetString("FrenchHill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;monster&gt;
        ///  &lt;number&gt;
        ///    &lt;base&gt;1&lt;/base&gt;
        ///  &lt;/number&gt;
        ///  &lt;name&gt;God of the Bloody Tongue&lt;/name&gt;
        ///  &lt;movement&gt;Normal&lt;/movement&gt;
        ///  &lt;awareness&gt;1&lt;/awareness&gt;
        ///  &lt;dimension&gt;Triangle&lt;/dimension&gt;
        ///  &lt;horror&gt;
        ///    &lt;rating&gt;-3&lt;/rating&gt;
        ///    &lt;damage&gt;3&lt;/damage&gt;
        ///  &lt;/horror&gt;
        ///  &lt;toughness&gt;4&lt;/toughness&gt;
        ///  &lt;combat&gt;
        ///    &lt;rating&gt;-4&lt;/rating&gt;
        ///    &lt;damage&gt;4&lt;/damage&gt;
        ///  &lt;/combat&gt;
        ///  &lt;abilities&gt;
        ///    &lt;ability name=&quot;Mask&quot; /&gt;
        ///    &lt;ability name=&quot;Endless&quot; /&gt;
        ///    &lt;ability name=&quot;Overwhelming&quot;&gt;1&lt;/ability&gt;
        ///    &lt;ability name=&quot;Nigh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string God_of_the_Bloody_Tongue {
            get {
                return ResourceManager.GetString("God_of_the_Bloody_Tongue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MerchantDistrict {
            get {
                return ResourceManager.GetString("MerchantDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MiskatonicUniversity {
            get {
                return ResourceManager.GetString("MiskatonicUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Northside {
            get {
                return ResourceManager.GetString("Northside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Rivertown {
            get {
                return ResourceManager.GetString("Rivertown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Southside {
            get {
                return ResourceManager.GetString("Southside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Uptown {
            get {
                return ResourceManager.GetString("Uptown", resourceCulture);
            }
        }
    }
}
