//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkhamHorrorCoreTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArkhamHorrorCoreTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;monster&gt;
        ///  &lt;number&gt;
        ///    &lt;base&gt;6&lt;/base&gt;
        ///  &lt;/number&gt;
        ///  &lt;name&gt;
        ///    &lt;eng&gt;Cultist&lt;/eng&gt;
        ///  &lt;/name&gt;
        ///  &lt;movement&gt;Normal&lt;/movement&gt;
        ///  &lt;awareness&gt;-3&lt;/awareness&gt;
        ///  &lt;dimension&gt;Moon&lt;/dimension&gt;
        ///  &lt;toughness&gt;1&lt;/toughness&gt;
        ///  &lt;combat&gt;
        ///    &lt;rating&gt;1&lt;/rating&gt;
        ///    &lt;damage&gt;1&lt;/damage&gt;
        ///  &lt;/combat&gt;
        ///  &lt;text&gt;
        ///    &lt;eng&gt;Ia! Ia! Cthulhu Fthagn! Ph&apos;nglui mglw&apos;nfah Cthulhu R&apos;lyeh wgah&apos;nagl fhtagn!&lt;/eng&gt;
        ///  &lt;/text&gt;
        ///&lt;/monster&gt;.
        /// </summary>
        internal static string Cultist {
            get {
                return ResourceManager.GetString("Cultist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;monster&gt;
        ///  &lt;number&gt;
        ///    &lt;base&gt;1&lt;/base&gt;
        ///  &lt;/number&gt;
        ///  &lt;name&gt;
        ///    &lt;eng&gt;God of the Bloody Tongue&lt;/eng&gt;
        ///  &lt;/name&gt;
        ///  &lt;movement&gt;Normal&lt;/movement&gt;
        ///  &lt;awareness&gt;1&lt;/awareness&gt;
        ///  &lt;dimension&gt;Triangle&lt;/dimension&gt;
        ///  &lt;horror&gt;
        ///    &lt;rating&gt;-3&lt;/rating&gt;
        ///    &lt;damage&gt;3&lt;/damage&gt;
        ///  &lt;/horror&gt;
        ///  &lt;toughness&gt;4&lt;/toughness&gt;
        ///  &lt;combat&gt;
        ///    &lt;rating&gt;-4&lt;/rating&gt;
        ///    &lt;damage&gt;4&lt;/damage&gt;
        ///  &lt;/combat&gt;
        ///  &lt;abilities&gt;
        ///    &lt;mask /&gt;
        ///    &lt;endless /&gt;
        ///    &lt;overwhelming&gt;1&lt;/overwhelming&gt;
        ///    &lt;nightmarish&gt;1&lt;/nightmarish&gt;
        ///  &lt;/abil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string God_of_the_Bloody_Tongue {
            get {
                return ResourceManager.GetString("God_of_the_Bloody_Tongue", resourceCulture);
            }
        }
    }
}
